# Permalinks
permalink:      /:year/:month/:day/:title

# Setup
title:          JVM. Blog.
paginate:       7
url:            "http://blog.andresteingress.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Andre Steingress
  url:          http://blog.andresteingress.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
  - jekyll-feed
