# Dependencies
markdown: 		  redcarpet

highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:day/:title

# Setup
title:            Blog
tagline:          'JVM Stuff.'
description:      'Andre Steingress'
url:              http://blog.andresteingress.com
twitter:          asteingr

author:
  name:           'Andre Steingress'
  url:            https://twitter.com/asteingr

paginate:         5

# Custom vars
version:          0.4.2.beta

github:
  repo:           https://github.com/andresteingress

encoding:         utf-8
